
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run migrate-and-dev
    ports:
      - "9002:9002"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/flicktrack?schema=public
      - REDIS_URL=redis://cache:6379
      - TMDB_API_KEY=${TMDB_API_KEY}
      - NEXT_PUBLIC_SITE_URL=http://localhost:9002
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flicktrack
      - PORT=9002
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=flicktrack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d flicktrack"]
      interval: 10s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8087:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
