// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6wZntvk94W-LnUcEzMkcOA3v9gvKdBg',
    appId: '1:550679240160:web:9988e86c0bfbda91785f85',
    messagingSenderId: '550679240160',
    projectId: 'filmfriend-kj51e',
    authDomain: 'filmfriend-kj51e.firebaseapp.com',
    storageBucket: 'filmfriend-kj51e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4JQnBqFLFeqTy1MLTf4b3_rij9MXjgPg',
    appId: '1:550679240160:android:3d96efe3aa04a8fc785f85',
    messagingSenderId: '550679240160',
    projectId: 'filmfriend-kj51e',
    storageBucket: 'filmfriend-kj51e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW2LtZrMvOryvglpCO6F7r02spMUCDuFs',
    appId: '1:550679240160:ios:37b7201a7637447c785f85',
    messagingSenderId: '550679240160',
    projectId: 'filmfriend-kj51e',
    storageBucket: 'filmfriend-kj51e.firebasestorage.app',
    iosBundleId: 'com.example.movieMagicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG6wZntvk94W-LnUcEzMkcOA3v9gvKdBg',
    appId: '1:550679240160:web:d7bc9ff714a9e2b2785f85',
    messagingSenderId: '550679240160',
    projectId: 'filmfriend-kj51e',
    authDomain: 'filmfriend-kj51e.firebaseapp.com',
    storageBucket: 'filmfriend-kj51e.firebasestorage.app',
  );
}
